
import { City, FoundItem } from './types';

export const FOUND_ITEMS_DATABASE: FoundItem[] = [];

export const SYSTEM_COLORS = {
  primary: '#064e3b', // Deep Emerald
  secondary: '#d97706', // Golden Amber
  accent: '#10b981', // Bright Green
};

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', flag: 'EN' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: 'AR' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', flag: 'UR' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: 'ID' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: 'TR' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: 'FR' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', flag: 'MS' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: 'BN' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: 'HI' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: 'DE' },
  { code: 'fa', name: 'Farsi', nativeName: 'فارسی', flag: 'FA' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: 'RU' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: 'ZH' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: 'ES' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: 'PT' },
  { code: 'ha', name: 'Hausa', nativeName: 'Hausa', flag: 'HA' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', flag: 'SW' },
  { code: 'so', name: 'Somali', nativeName: 'Soomaali', flag: 'SO' },
] as const;

export const COUNTRIES = [
  { name: 'Saudi Arabia', code: '+966', flag: '🇸🇦', iso: 'sa' },
  { name: 'Afghanistan', code: '+93', flag: '🇦🇫', iso: 'af' },
  { name: 'Åland Islands', code: '+358', flag: '🇦🇽', iso: 'ax' },
  { name: 'Albania', code: '+355', flag: '🇦🇱', iso: 'al' },
  { name: 'Algeria', code: '+213', flag: '🇩🇿', iso: 'dz' },
  { name: 'American Samoa', code: '+1684', flag: '🇦🇸', iso: 'as' },
  { name: 'Andorra', code: '+376', flag: '🇦🇩', iso: 'ad' },
  { name: 'Angola', code: '+244', flag: '🇦🇴', iso: 'ao' },
  { name: 'Anguilla', code: '+1264', flag: '🇦🇮', iso: 'ai' },
  { name: 'Antarctica', code: '+672', flag: '🇦🇶', iso: 'aq' },
  { name: 'Antigua and Barbuda', code: '+1268', flag: '🇦🇬', iso: 'ag' },
  { name: 'Argentina', code: '+54', flag: '🇦🇷', iso: 'ar' },
  { name: 'Armenia', code: '+374', flag: '🇦🇲', iso: 'am' },
  { name: 'Aruba', code: '+297', flag: '🇦🇼', iso: 'aw' },
  { name: 'Australia', code: '+61', flag: '🇦🇺', iso: 'au' },
  { name: 'Austria', code: '+43', flag: '🇦🇹', iso: 'at' },
  { name: 'Azerbaijan', code: '+994', flag: '🇦🇿', iso: 'az' },
  { name: 'Bahamas', code: '+1242', flag: '🇧🇸', iso: 'bs' },
  { name: 'Bahrain', code: '+973', flag: '🇧🇭', iso: 'bh' },
  { name: 'Bangladesh', code: '+880', flag: '🇧🇩', iso: 'bd' },
  { name: 'Barbados', code: '+1246', flag: '🇧🇧', iso: 'bb' },
  { name: 'Belarus', code: '+375', flag: '🇧🇾', iso: 'by' },
  { name: 'Belgium', code: '+32', flag: '🇧🇪', iso: 'be' },
  { name: 'Belize', code: '+501', flag: '🇧🇿', iso: 'bz' },
  { name: 'Benin', code: '+229', flag: '🇧🇯', iso: 'bj' },
  { name: 'Bermuda', code: '+1441', flag: '🇧🇲', iso: 'bm' },
  { name: 'Bhutan', code: '+975', flag: '🇧🇹', iso: 'bt' },
  { name: 'Bolivia', code: '+591', flag: '🇧🇴', iso: 'bo' },
  { name: 'Bosnia and Herzegovina', code: '+387', flag: '🇧🇦', iso: 'ba' },
  { name: 'Botswana', code: '+267', flag: '🇧🇼', iso: 'bw' },
  { name: 'Bouvet Island', code: '+47', flag: '🇧🇻', iso: 'bv' },
  { name: 'Brazil', code: '+55', flag: '🇧🇷', iso: 'br' },
  { name: 'British Indian Ocean Territory', code: '+246', flag: '🇮🇴', iso: 'io' },
  { name: 'Brunei Darussalam', code: '+673', flag: '🇧🇳', iso: 'bn' },
  { name: 'Bulgaria', code: '+359', flag: '🇧🇬', iso: 'bg' },
  { name: 'Burkina Faso', code: '+226', flag: '🇧🇫', iso: 'bf' },
  { name: 'Burundi', code: '+257', flag: '🇧🇮', iso: 'bi' },
  { name: 'Cambodia', code: '+855', flag: '🇰🇭', iso: 'kh' },
  { name: 'Cameroon', code: '+237', flag: '🇨🇲', iso: 'cm' },
  { name: 'Canada', code: '+1', flag: '🇨🇦', iso: 'ca' },
  { name: 'Cape Verde', code: '+238', flag: '🇨🇻', iso: 'cv' },
  { name: 'Cayman Islands', code: '+1345', flag: '🇰🇾', iso: 'ky' },
  { name: 'Central African Republic', code: '+236', flag: '🇨🇫', iso: 'cf' },
  { name: 'Chad', code: '+235', flag: '🇹🇩', iso: 'td' },
  { name: 'Chile', code: '+56', flag: '🇨🇱', iso: 'cl' },
  { name: 'China', code: '+86', flag: '🇨🇳', iso: 'cn' },
  { name: 'Christmas Island', code: '+61', flag: '🇨🇽', iso: 'cx' },
  { name: 'Cocos (Keeling) Islands', code: '+61', flag: '🇨🇨', iso: 'cc' },
  { name: 'Colombia', code: '+57', flag: '🇨🇴', iso: 'co' },
  { name: 'Comoros', code: '+269', flag: '🇰🇲', iso: 'km' },
  { name: 'Congo', code: '+242', flag: '🇨🇬', iso: 'cg' },
  { name: 'Congo, The Democratic Republic of the Congo', code: '+243', flag: '🇨🇩', iso: 'cd' },
  { name: 'Cook Islands', code: '+682', flag: '🇨🇰', iso: 'ck' },
  { name: 'Costa Rica', code: '+506', flag: '🇨🇷', iso: 'cr' },
  { name: 'Côte d\'Ivoire', code: '+225', flag: '🇨🇮', iso: 'ci' },
  { name: 'Croatia', code: '+385', flag: '🇭🇷', iso: 'hr' },
  { name: 'Cuba', code: '+53', flag: '🇨🇺', iso: 'cu' },
  { name: 'Cyprus', code: '+357', flag: '🇨🇾', iso: 'cy' },
  { name: 'Czech Republic', code: '+420', flag: '🇨🇿', iso: 'cz' },
  { name: 'Denmark', code: '+45', flag: '🇩🇰', iso: 'dk' },
  { name: 'Djibouti', code: '+253', flag: '🇩🇯', iso: 'dj' },
  { name: 'Dominica', code: '+1767', flag: '🇩🇲', iso: 'dm' },
  { name: 'Dominican Republic', code: '+1849', flag: '🇩🇴', iso: 'do' },
  { name: 'Ecuador', code: '+593', flag: '🇪🇨', iso: 'ec' },
  { name: 'Egypt', code: '+20', flag: '🇪🇬', iso: 'eg' },
  { name: 'El Salvador', code: '+503', flag: '🇸🇻', iso: 'sv' },
  { name: 'Equatorial Guinea', code: '+240', flag: '🇬🇶', iso: 'gq' },
  { name: 'Eritrea', code: '+291', flag: '🇪🇷', iso: 'er' },
  { name: 'Estonia', code: '+372', flag: '🇪🇪', iso: 'ee' },
  { name: 'Ethiopia', code: '+251', flag: '🇪🇹', iso: 'et' },
  { name: 'Falkland Islands (Malvinas)', code: '+500', flag: '🇫🇰', iso: 'fk' },
  { name: 'Faroe Islands', code: '+298', flag: '🇫🇴', iso: 'fo' },
  { name: 'Fiji', code: '+679', flag: '🇫🇯', iso: 'fj' },
  { name: 'Finland', code: '+358', flag: '🇫🇮', iso: 'fi' },
  { name: 'France', code: '+33', flag: '🇫🇷', iso: 'fr' },
  { name: 'French Guiana', code: '+594', flag: '🇬🇫', iso: 'gf' },
  { name: 'French Polynesia', code: '+689', flag: '🇵🇫', iso: 'pf' },
  { name: 'French Southern Territories', code: '+262', flag: '🇹🇫', iso: 'tf' },
  { name: 'Gabon', code: '+241', flag: '🇬🇦', iso: 'ga' },
  { name: 'Gambia', code: '+220', flag: '🇬🇲', iso: 'gm' },
  { name: 'Georgia', code: '+995', flag: '🇬🇪', iso: 'ge' },
  { name: 'Germany', code: '+49', flag: '🇩🇪', iso: 'de' },
  { name: 'Ghana', code: '+233', flag: '🇬🇭', iso: 'gh' },
  { name: 'Gibraltar', code: '+350', flag: '🇬🇮', iso: 'gi' },
  { name: 'Greece', code: '+30', flag: '🇬🇷', iso: 'gr' },
  { name: 'Greenland', code: '+299', flag: '🇬🇱', iso: 'gl' },
  { name: 'Grenada', code: '+1473', flag: '🇬🇩', iso: 'gd' },
  { name: 'Guadeloupe', code: '+590', flag: '🇬🇵', iso: 'gp' },
  { name: 'Guam', code: '+1671', flag: '🇬🇺', iso: 'gu' },
  { name: 'Guatemala', code: '+502', flag: '🇬🇹', iso: 'gt' },
  { name: 'Guernsey', code: '+44', flag: '🇬🇬', iso: 'gg' },
  { name: 'Guinea', code: '+224', flag: '🇬🇳', iso: 'gn' },
  { name: 'Guinea-Bissau', code: '+245', flag: '🇬🇼', iso: 'gw' },
  { name: 'Guyana', code: '+592', flag: '🇬🇾', iso: 'gy' },
  { name: 'Haiti', code: '+509', flag: '🇭🇹', iso: 'ht' },
  { name: 'Heard Island and Mcdonald Islands', code: '+672', flag: '🇭🇲', iso: 'hm' },
  { name: 'Holy See (Vatican City State)', code: '+379', flag: '🇻🇦', iso: 'va' },
  { name: 'Honduras', code: '+504', flag: '🇭🇳', iso: 'hn' },
  { name: 'Hong Kong', code: '+852', flag: '🇭🇰', iso: 'hk' },
  { name: 'Hungary', code: '+36', flag: '🇭🇺', iso: 'hu' },
  { name: 'Iceland', code: '+354', flag: '🇮🇸', iso: 'is' },
  { name: 'India', code: '+91', flag: '🇮🇳', iso: 'in' },
  { name: 'Iran', code: '+98', flag: '🇮🇷', iso: 'ir' },
  { name: 'Iraq', code: '+964', flag: '🇮🇶', iso: 'iq' },
  { name: 'Ireland', code: '+353', flag: '🇮🇪', iso: 'ie' },
  { name: 'Isle of Man', code: '+44', flag: '🇮🇲', iso: 'im' },
  { name: 'Italy', code: '+39', flag: '🇮🇹', iso: 'it' },
  { name: 'Jamaica', code: '+1876', flag: '🇯🇲', iso: 'jm' },
  { name: 'Japan', code: '+81', flag: '🇯🇵', iso: 'jp' },
  { name: 'Jersey', code: '+44', flag: '🇯🇪', iso: 'je' },
  { name: 'Jordan', code: '+962', flag: '🇯🇴', iso: 'jo' },
  { name: 'Kazakhstan', code: '+7', flag: '🇰🇿', iso: 'kz' },
  { name: 'Kenya', code: '+254', flag: '🇰🇪', iso: 'ke' },
  { name: 'Kiribati', code: '+686', flag: '🇰🇮', iso: 'ki' },
  { name: 'Korea, Democratic People\'s Republic of Korea', code: '+850', flag: '🇰🇵', iso: 'kp' },
  { name: 'Korea, Republic of South Korea', code: '+82', flag: '🇰🇷', iso: 'kr' },
  { name: 'Kosovo', code: '+383', flag: '🇽🇰', iso: 'xk' },
  { name: 'Kuwait', code: '+965', flag: '🇰🇼', iso: 'kw' },
  { name: 'Kyrgyzstan', code: '+996', flag: '🇰🇬', iso: 'kg' },
  { name: 'Laos', code: '+856', flag: '🇱🇦', iso: 'la' },
  { name: 'Latvia', code: '+371', flag: '🇱🇻', iso: 'lv' },
  { name: 'Lebanon', code: '+961', flag: '🇱🇧', iso: 'lb' },
  { name: 'Lesotho', code: '+266', flag: '🇱🇸', iso: 'ls' },
  { name: 'Liberia', code: '+231', flag: '🇱🇷', iso: 'lr' },
  { name: 'Libyan Arab Jamahiriya', code: '+218', flag: '🇱🇾', iso: 'ly' },
  { name: 'Liechtenstein', code: '+423', flag: '🇱🇮', iso: 'li' },
  { name: 'Lithuania', code: '+370', flag: '🇱🇹', iso: 'lt' },
  { name: 'Luxembourg', code: '+352', flag: '🇱🇺', iso: 'lu' },
  { name: 'Macao', code: '+853', flag: '🇲🇴', iso: 'mo' },
  { name: 'Macedonia', code: '+389', flag: '🇲🇰', iso: 'mk' },
  { name: 'Madagascar', code: '+261', flag: '🇲🇬', iso: 'mg' },
  { name: 'Malawi', code: '+265', flag: '🇲🇼', iso: 'mw' },
  { name: 'Malaysia', code: '+60', flag: '🇲🇾', iso: 'my' },
  { name: 'Maldives', code: '+960', flag: '🇲🇻', iso: 'mv' },
  { name: 'Mali', code: '+223', flag: '🇲🇱', iso: 'ml' },
  { name: 'Malta', code: '+356', flag: '🇲🇹', iso: 'mt' },
  { name: 'Marshall Islands', code: '+692', flag: '🇲🇭', iso: 'mh' },
  { name: 'Martinique', code: '+596', flag: '🇲🇶', iso: 'mq' },
  { name: 'Mauritania', code: '+222', flag: '🇲🇷', iso: 'mr' },
  { name: 'Mauritius', code: '+230', flag: '🇲🇺', iso: 'mu' },
  { name: 'Mayotte', code: '+262', flag: '🇾🇹', iso: 'yt' },
  { name: 'Mexico', code: '+52', flag: '🇲🇽', iso: 'mx' },
  { name: 'Micronesia, Federated States of Micronesia', code: '+691', flag: '🇫🇲', iso: 'fm' },
  { name: 'Moldova', code: '+373', flag: '🇲🇩', iso: 'md' },
  { name: 'Monaco', code: '+377', flag: '🇲🇨', iso: 'mc' },
  { name: 'Mongolia', code: '+976', flag: '🇲🇳', iso: 'mn' },
  { name: 'Montenegro', code: '+382', flag: '🇲🇪', iso: 'me' },
  { name: 'Montserrat', code: '+1664', flag: '🇲🇸', iso: 'ms' },
  { name: 'Morocco', code: '+212', flag: '🇲🇦', iso: 'ma' },
  { name: 'Mozambique', code: '+258', flag: '🇲🇿', iso: 'mz' },
  { name: 'Myanmar', code: '+95', flag: '🇲🇲', iso: 'mm' },
  { name: 'Namibia', code: '+264', flag: '🇳🇦', iso: 'na' },
  { name: 'Nauru', code: '+674', flag: '🇳🇷', iso: 'nr' },
  { name: 'Nepal', code: '+977', flag: '🇳🇵', iso: 'np' },
  { name: 'Netherlands', code: '+31', flag: '🇳🇱', iso: 'nl' },
  { name: 'Netherlands Antilles', code: '+599', flag: '', iso: 'an' },
  { name: 'New Caledonia', code: '+687', flag: '🇳🇨', iso: 'nc' },
  { name: 'New Zealand', code: '+64', flag: '🇳🇿', iso: 'nz' },
  { name: 'Nicaragua', code: '+505', flag: '🇳🇮', iso: 'ni' },
  { name: 'Niger', code: '+227', flag: '🇳🇪', iso: 'ne' },
  { name: 'Nigeria', code: '+234', flag: '🇳🇬', iso: 'ng' },
  { name: 'Niue', code: '+683', flag: '🇳🇺', iso: 'nu' },
  { name: 'Norfolk Island', code: '+672', flag: '🇳🇫', iso: 'nf' },
  { name: 'Northern Mariana Islands', code: '+1670', flag: '🇲🇵', iso: 'mp' },
  { name: 'Norway', code: '+47', flag: '🇳🇴', iso: 'no' },
  { name: 'Oman', code: '+968', flag: '🇴🇲', iso: 'om' },
  { name: 'Pakistan', code: '+92', flag: '🇵🇰', iso: 'pk' },
  { name: 'Palau', code: '+680', flag: '🇵🇼', iso: 'pw' },
  { name: 'Palestine', code: '+970', flag: '🇵🇸', iso: 'ps' },
  { name: 'Panama', code: '+507', flag: '🇵🇦', iso: 'pa' },
  { name: 'Papua New Guinea', code: '+675', flag: '🇵🇬', iso: 'pg' },
  { name: 'Paraguay', code: '+595', flag: '🇵🇾', iso: 'py' },
  { name: 'Peru', code: '+51', flag: '🇵🇪', iso: 'pe' },
  { name: 'Philippines', code: '+63', flag: '🇵🇭', iso: 'ph' },
  { name: 'Pitcairn', code: '+64', flag: '🇵🇳', iso: 'pn' },
  { name: 'Poland', code: '+48', flag: '🇵🇱', iso: 'pl' },
  { name: 'Portugal', code: '+351', flag: '🇵🇹', iso: 'pt' },
  { name: 'Puerto Rico', code: '+1939', flag: '🇵🇷', iso: 'pr' },
  { name: 'Qatar', code: '+974', flag: '🇶🇦', iso: 'qa' },
  { name: 'Romania', code: '+40', flag: '🇷🇴', iso: 'ro' },
  { name: 'Russia', code: '+7', flag: '🇷🇺', iso: 'ru' },
  { name: 'Rwanda', code: '+250', flag: '🇷🇼', iso: 'rw' },
  { name: 'Reunion', code: '+262', flag: '🇷🇪', iso: 're' },
  { name: 'Saint Barthelemy', code: '+590', flag: '🇧🇱', iso: 'bl' },
  { name: 'Saint Helena, Ascension and Tristan Da Cunha', code: '+290', flag: '🇸🇭', iso: 'sh' },
  { name: 'Saint Kitts and Nevis', code: '+1869', flag: '🇰🇳', iso: 'kn' },
  { name: 'Saint Lucia', code: '+1758', flag: '🇱🇨', iso: 'lc' },
  { name: 'Saint Martin', code: '+590', flag: '🇲🇫', iso: 'mf' },
  { name: 'Saint Pierre and Miquelon', code: '+508', flag: '🇵🇲', iso: 'pm' },
  { name: 'Saint Vincent and the Grenadines', code: '+1784', flag: '🇻🇨', iso: 'vc' },
  { name: 'Samoa', code: '+685', flag: '🇼🇸', iso: 'ws' },
  { name: 'San Marino', code: '+378', flag: '🇸🇲', iso: 'sm' },
  { name: 'Sao Tome and Principe', code: '+239', flag: '🇸🇹', iso: 'st' },
  { name: 'Senegal', code: '+221', flag: '🇸🇳', iso: 'sn' },
  { name: 'Serbia', code: '+381', flag: '🇷🇸', iso: 'rs' },
  { name: 'Seychelles', code: '+248', flag: '🇸🇨', iso: 'sc' },
  { name: 'Sierra Leone', code: '+232', flag: '🇸🇱', iso: 'sl' },
  { name: 'Singapore', code: '+65', flag: '🇸🇬', iso: 'sg' },
  { name: 'Slovakia', code: '+421', flag: '🇸🇰', iso: 'sk' },
  { name: 'Slovenia', code: '+386', flag: '🇸🇮', iso: 'si' },
  { name: 'Solomon Islands', code: '+677', flag: '🇸🇧', iso: 'sb' },
  { name: 'Somalia', code: '+252', flag: '🇸🇴', iso: 'so' },
  { name: 'South Africa', code: '+27', flag: '🇿🇦', iso: 'za' },
  { name: 'South Sudan', code: '+211', flag: '🇸🇸', iso: 'ss' },
  { name: 'South Georgia and the South Sandwich Islands', code: '+500', flag: '🇬🇸', iso: 'gs' },
  { name: 'Spain', code: '+34', flag: '🇪🇸', iso: 'es' },
  { name: 'Sri Lanka', code: '+94', flag: '🇱🇰', iso: 'lk' },
  { name: 'Sudan', code: '+249', flag: '🇸🇩', iso: 'sd' },
  { name: 'Suriname', code: '+597', flag: '🇸🇷', iso: 'sr' },
  { name: 'Svalbard and Jan Mayen', code: '+47', flag: '🇸🇯', iso: 'sj' },
  { name: 'Swaziland', code: '+268', flag: '🇸🇿', iso: 'sz' },
  { name: 'Sweden', code: '+46', flag: '🇸🇪', iso: 'se' },
  { name: 'Switzerland', code: '+41', flag: '🇨🇭', iso: 'ch' },
  { name: 'Syrian Arab Republic', code: '+963', flag: '🇸🇾', iso: 'sy' },
  { name: 'Taiwan', code: '+886', flag: '🇹🇼', iso: 'tw' },
  { name: 'Tajikistan', code: '+992', flag: '🇹🇯', iso: 'tj' },
  { name: 'Tanzania, United Republic of Tanzania', code: '+255', flag: '🇹🇿', iso: 'tz' },
  { name: 'Thailand', code: '+66', flag: '🇹🇭', iso: 'th' },
  { name: 'Timor-Leste', code: '+670', flag: '🇹🇱', iso: 'tl' },
  { name: 'Togo', code: '+228', flag: '🇹🇬', iso: 'tg' },
  { name: 'Tokelau', code: '+690', flag: '🇹🇰', iso: 'tk' },
  { name: 'Tonga', code: '+676', flag: '🇹🇴', iso: 'to' },
  { name: 'Trinidad and Tobago', code: '+1868', flag: '🇹🇹', iso: 'tt' },
  { name: 'Tunisia', code: '+216', flag: '🇹🇳', iso: 'tn' },
  { name: 'Turkey', code: '+90', flag: '🇹🇷', iso: 'tr' },
  { name: 'Turkmenistan', code: '+993', flag: '🇹🇲', iso: 'tm' },
  { name: 'Turks and Caicos Islands', code: '+1649', flag: '🇹🇨', iso: 'tc' },
  { name: 'Tuvalu', code: '+688', flag: '🇹🇻', iso: 'tv' },
  { name: 'Uganda', code: '+256', flag: '🇺🇬', iso: 'ug' },
  { name: 'Ukraine', code: '+380', flag: '🇺🇦', iso: 'ua' },
  { name: 'United Arab Emirates', code: '+971', flag: '🇦🇪', iso: 'ae' },
  { name: 'United Kingdom', code: '+44', flag: '🇬🇧', iso: 'gb' },
  { name: 'United States', code: '+1', flag: '🇺🇸', iso: 'us' },
  { name: 'Uruguay', code: '+598', flag: '🇺🇾', iso: 'uy' },
  { name: 'Uzbekistan', code: '+998', flag: '🇺🇿', iso: 'uz' },
  { name: 'Vanuatu', code: '+678', flag: '🇻🇺', iso: 'vu' },
  { name: 'Venezuela', code: '+58', flag: '🇻🇪', iso: 've' },
  { name: 'Vietnam', code: '+84', flag: '🇻🇳', iso: 'vn' },
  { name: 'Virgin Islands, British', code: '+1284', flag: '🇻🇬', iso: 'vg' },
  { name: 'Virgin Islands, U.S.', code: '+1340', flag: '🇻🇮', iso: 'vi' },
  { name: 'Wallis and Futuna', code: '+681', flag: '🇼🇫', iso: 'wf' },
  { name: 'Yemen', code: '+967', flag: '🇾🇪', iso: 'ye' },
  { name: 'Zambia', code: '+260', flag: '🇿🇲', iso: 'zm' },
  { name: 'Zimbabwe', code: '+263', flag: '🇿🇼', iso: 'zw' },
];
